language: node_js
node_js:
  - 6
script:
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: I6HPvFK4j9ygcKegYzhCyBtnvUoyiy/YVGz/UfG/7xmdrNXtGWEzR1M4Mq0JP7peQdXqwAQv/XGKaqTBh1oBFJcaQSKhKes1VMyJ5rpX9QgcHWoggsHIrcYINpmCqv8aNzqz6OWpkB08NPT+2v32E4fIR9pBv5nZxqEoAqgR2ncrB811VLGWM4FpqcHTHPCT+D6RJ3RyuqxNfZWLadFzmgb24Rqwb/Nl2XQe7jTxw35oT8tBb67XsaI0oOy7fEFtNfaY6Mcrrp38J2OREN0+hGv6ODh3vRVQZ0D1NxJbcRBdU17Qh2rSBSvvllZye4oySbXY04JjeVEN0Ktancb8cZOTBwdrAf+xu8uUx5Tgz+mVhoD3t92HPzToIYP1Cp2jk7mkVXn4CddHthbhF4UTMmEjp4CLnPH15WaySDfwCzgzrhMCuKLeqDhYVboXipRcq9fmPQzs0IE6gs71bG/N6hPuthz/alv9wPIekKQ8RQ+N77+lAd08RvoK4BEz0SyFki43M0Nk4eaQWeIUyGi9+e+BFwdVI54ysncdM7m+05Stu9cfy+qWtftiALgLnXW4xCYzhmgYPv9EuUJOLoIzEKCVXDvP3nj3ndrjJiFRN5DzpbtmuzQ7qvrdjf6zvmfcnCK0YNu94ozIMHjguqknKGuSaML+BO/O+ewkUMrvmjA=
  app:
    dev: cdc-java-bootcamp